/**
 * Seed list of prominent Indian engineering colleges & universities
 * for searchable autocomplete during student and TPO registration.
 */
export const COLLEGE_LIST: string[] = [
  // Host Institution
  'Sanjivani College of Engineering, Kopargaon',
  'Sanjivani Rural Education Society, Kopargaon',

  // Indian Institutes of Technology (All 23 IITs)
  'Indian Institute of Technology Bombay (IIT Bombay)',
  'Indian Institute of Technology Delhi (IIT Delhi)',
  'Indian Institute of Technology Madras (IIT Madras)',
  'Indian Institute of Technology Kanpur (IIT Kanpur)',
  'Indian Institute of Technology Kharagpur (IIT Kharagpur)',
  'Indian Institute of Technology Roorkee (IIT Roorkee)',
  'Indian Institute of Technology Guwahati (IIT Guwahati)',
  'Indian Institute of Technology Hyderabad (IIT Hyderabad)',
  'Indian Institute of Technology (BHU) Varanasi',
  'Indian Institute of Technology (ISM) Dhanbad',
  'Indian Institute of Technology Indore (IIT Indore)',
  'Indian Institute of Technology Ropar (IIT Ropar)',
  'Indian Institute of Technology Mandi (IIT Mandi)',
  'Indian Institute of Technology Gandhinagar (IIT Gandhinagar)',
  'Indian Institute of Technology Jodhpur (IIT Jodhpur)',
  'Indian Institute of Technology Patna (IIT Patna)',
  'Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)',
  'Indian Institute of Technology Tirupati (IIT Tirupati)',
  'Indian Institute of Technology Palakkad (IIT Palakkad)',
  'Indian Institute of Technology Dharwad (IIT Dharwad)',
  'Indian Institute of Technology Bhilai (IIT Bhilai)',
  'Indian Institute of Technology Goa (IIT Goa)',
  'Indian Institute of Technology Jammu (IIT Jammu)',

  // BITS Campuses
  'Birla Institute of Technology and Science, Pilani (BITS Pilani)',
  'BITS Pilani - K.K. Birla Goa Campus',
  'BITS Pilani - Hyderabad Campus',

  // Major IIITs
  'International Institute of Information Technology, Hyderabad (IIIT Hyderabad)',
  'International Institute of Information Technology, Bangalore (IIIT Bangalore)',
  'Indraprastha Institute of Information Technology Delhi (IIIT Delhi)',
  'Indian Institute of Information Technology, Allahabad (IIIT Allahabad)',
  'Indian Institute of Information Technology, Design and Manufacturing Gwalior (ABV-IIITM)',
  'Indian Institute of Information Technology, Design and Manufacturing Jabalpur (IIITDMJ)',
  'Indian Institute of Information Technology, Design and Manufacturing Kancheepuram (IIITDM)',
  'Indian Institute of Information Technology, Lucknow (IIIT Lucknow)',

  // National Institutes of Technology (Top NITs)
  'National Institute of Technology, Tiruchirappalli (NIT Trichy)',
  'National Institute of Technology Karnataka, Surathkal (NIT Surathkal)',
  'National Institute of Technology, Warangal (NIT Warangal)',
  'Visvesvaraya National Institute of Technology, Nagpur (VNIT Nagpur)',
  'National Institute of Technology, Calicut (NIT Calicut)',
  'National Institute of Technology, Rourkela (NIT Rourkela)',
  'Malaviya National Institute of Technology, Jaipur (MNIT Jaipur)',
  'Motilal Nehru National Institute of Technology, Allahabad (MNNIT Allahabad)',
  'Sardar Vallabhbhai National Institute of Technology, Surat (SVNIT Surat)',
  'Maulana Azad National Institute of Technology, Bhopal (MANIT Bhopal)',
  'Dr. B. R. Ambedkar National Institute of Technology, Jalandhar (NIT Jalandhar)',
  'National Institute of Technology, Kurukshetra (NIT Kurukshetra)',
  'National Institute of Technology, Durgapur (NIT Durgapur)',
  'National Institute of Technology, Silchar (NIT Silchar)',
  'National Institute of Technology, Raipur (NIT Raipur)',
  'National Institute of Technology, Patna (NIT Patna)',
  'National Institute of Technology, Hamirpur (NIT Hamirpur)',
  'National Institute of Technology, Meghalaya (NIT Meghalaya)',
  'National Institute of Technology, Goa (NIT Goa)',

  // Top State, Central & Premier Engineering Institutions
  'COEP Technological University, Pune',
  'Veermata Jijabai Technological Institute (VJTI), Mumbai',
  'Pune Institute of Computer Technology (PICT), Pune',
  'Sardar Patel Institute of Technology (SPIT), Mumbai',
  'Vishwakarma Institute of Technology (VIT), Pune',
  'MKSSS Cummins College of Engineering for Women, Pune',
  'Walchand College of Engineering, Sangli',
  'Government College of Engineering, Aurangabad (GCEA)',
  'Delhi Technological University (DTU), Delhi',
  'Netaji Subhas University of Technology (NSUT), Delhi',
  'Jadavpur University (Faculty of Engineering & Technology), Kolkata',
  'Vellore Institute of Technology (VIT), Vellore',
  'Thapar Institute of Engineering and Technology, Patiala',
  'RV College of Engineering (RVCE), Bengaluru',
  'BMS College of Engineering (BMSCE), Bengaluru',
  'M. S. Ramaiah Institute of Technology (MSRIT), Bengaluru',
  'PES University, Bengaluru',
  'PSG College of Technology, Coimbatore',
  'College of Engineering, Guindy (Anna University), Chennai',
  'Manipal Institute of Technology (MIT), Manipal',
  'SRM Institute of Science and Technology, Kattankulathur',
  'Amrita Vishwa Vidyapeetham, Coimbatore',
  'Institute of Chemical Technology (ICT), Mumbai',
  'Indian Institute of Engineering Science and Technology, Shibpur (IIEST Shibpur)',
  'Harcourt Butler Technical University (HBTU), Kanpur',
  'Punjab Engineering College (PEC), Chandigarh',
  'Birla Institute of Technology, Mesra (BIT Mesra)',
  'MIT World Peace University (MIT-WPU), Pune',
];
